# Generated by Django 4.2.13 on 2024-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0002_restaurant_admin_password_restaurant_resturant_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='resturant_admin',
            field=models.EmailField(max_length=254),
        ),
    ]
