# Generated by Django 4.2.13 on 2024-05-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0003_alter_restaurant_resturant_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='time_for_delivery',
        ),
    ]
