# Generated by Django 4.2.13 on 2024-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0004_remove_restaurant_time_for_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='admin_password',
            new_name='password',
        ),
    ]
