# Generated by Django 4.2.13 on 2024-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0005_rename_admin_password_restaurant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
